name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: Install terraform-docs
        run: |
          mkdir -p terraform-docs-extract
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v${VERSION}/terraform-docs-v${VERSION}-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz -C terraform-docs-extract
          sudo mv terraform-docs-extract/terraform-docs /usr/local/bin/terraform-docs
          rm -rf terraform-docs-extract
          rm -f terraform-docs.tar.gz
          terraform-docs -v
        env:
          VERSION: 0.20.0

      - name: Install markdown-link-check
        run: |
          npm install -g markdown-link-check

      - name: Run all checks
        run: |
          make all

      - name: Check for changes
        run: |
          git diff --exit-code || (echo "There are changes in the repository. Please commit them." && exit 1)
          echo "No changes detected."

  terraform-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform-version:
          - "1.9.0"
          - "1.10.0"
          - "1.11.0"
          - "1.12.0"
          - "1.13.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Terraform ${{ matrix.terraform-version }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform-version }}

      - name: Run make init
        run: make init
